SELECT 
    H.CAR_ID,
    CASE
        WHEN (SELECT COUNT(*) FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
              WHERE H.CAR_ID = CAR_ID
              AND START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16') THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
GROUP BY H.CAR_ID
ORDER BY H.CAR_ID DESC