SELECT I.ITEM_ID, I.ITEM_NAME, I.RARITY FROM ITEM_INFO I
INNER JOIN ITEM_TREE T ON I.ITEM_ID = T.ITEM_ID
INNER JOIN ITEM_INFO I2 ON T.PARENT_ITEM_ID = I2.ITEM_ID
WHERE I2.RARITY = 'RARE'
ORDER BY I.ITEM_ID DESC